version: "3.8"

services:
  api_8000:
    build:
      context: ./api_8000
    ports:
      - "8000:8000"
    container_name: fastapi_8000
    restart: unless-stopped
    env_file:
      - ./api_8000/.env

  api_8001:
    build:
      context: ./api_8001
    ports:
      - "8001:8001"
    container_name: fastapi_8001
    restart: unless-stopped
    env_file:
      - ./api_8001/.env